### ISSUE TITLE
[Problema] Erro ao acessar a página de curso para obter número de aulas

### ISSUE THREAD

**Issue by DouglasMartins1999** [ceelsoin/alura-video-scrapper#1]
Por algum motivo, não consigo utilizar a ferramenta. Passo todos os argumentos corretamente, porém quando ele tenta acessar a página do curso, ocorre um erro de timeout e finaliza o script. O problema é que eu consigo acessar diretamente a página normalmente pelo navegador.

Atualmente usando Windows 10, Node 8.11.3 e NPM 5.6.0
Testei também no Deepin 15.7, Node 9.11.2 e NPM 5.6.0 e obtive o mesmo resultado.

Segue um screenshot do erro
![captura de tela 122](https://user-images.githubusercontent.com/13039437/47265951-417c8600-d506-11e8-8e66-b699337d85d0.png)

Obs: Para testar no linux foi necessário remover o stay-awake.
Obs²: Também tentei definir todas as dependências para suas versões exatas, deletar ./node_modules e dar novamente npm i, porém sem sucesso, o erro persiste.

**Comment by ceelsoin** [comment]
Legal ver que estão usando minha ferramenta :)
Você pode trocar na constante GLOBAL_CONFIG a variavel handless de true para false, ele irá exibir uma janela do navegador interno e você poderá ver o que acontece na íntegra

**Comment by DouglasMartins1999** [comment]
Troquei, ele simplesmente me exibe duas abas em branco (about:blank) e o erro acontece como antes.

**Comment by ceelsoin** [comment]
O método awaitforNavigation() é a promise que aguarda o fim da navegação, para que então prossiga com o restante das atividades. Tive problemas em dias que o servidor da alura simplesmente estava lento, talvez aguardar a navegação tenha sido um problema...

Agora sobre o login, nos testes de estresse, foram baixados todos os cursos de A á J e não tivemos problema com a alura nesse sentido, o único problema detectado é que após um certo tempo (nos testes 3 dias) com o mesmo IP a Vímeo bloqueou o acesso do robô, porém facilmente resolvido com a troca do IP (no meu caso reiniciando o modem de internet). E o login frequente, a cada download realmente é necessário, principalmente em casos de contas compartilhadas, pois a cada login a Alura derruba a sessão de outras pessoas logadas, sendo obrigatório fazer isso a cada vídeo, podendo acontecer inclusive se você acessar a Alura enquanto seu robô estiver trabalhando.
